services:
  - type: web
    name: zeropass-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    rootDir: backend
    envVars:
      - key: CORS_ORIGINS
        value: https://zeropass-firewall-simulator.vercel.app,https://zeropass-firewall-simulator-syn3-malaquis-projects.vercel.app,https://zeropass-firewall-simulator-git-main-syn3-malaquis-projects.vercel.app,http://localhost:3000
      - key: PYTHON_VERSION
        value: 3.9.0
    plan: free
    healthCheckPath: /health 