services:
  - type: web
    name: zeropass-backend
    runtime: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT --workers 2
    envVars:
      - key: CORS_ORIGINS
        value: "https://zeropass-firewall-simulator.vercel.app,https://*.vercel.app"
      - key: PYTHONPATH
        value: ./backend
    healthCheckPath: /health 